# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Temp', max_length=255),
            preserve_default=False,
        ),
    ]
